language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - cd ./LombardClient
  - npm install
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod
